In [32]:
import tensorflow as tf

In [33]:
tf.__version__

'2.3.0'

In [34]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6, 7])

In [35]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [36]:
for ele in dataset:
    print(ele)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)


In [37]:
for ele in dataset:
    print(ele.numpy())

1
2
3
4
5
6
7


In [38]:
dataset = tf.data.Dataset.from_tensor_slices([[1, 2], [3, 4], [5, 6]])

In [39]:
dataset

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [40]:
for ele in dataset:
    print(ele.numpy())

[1 2]
[3 4]
[5 6]


In [41]:
dataset_dic = tf.data.Dataset.from_tensor_slices({'a':[1,2,3,4],
                                                  'b':[6,7,8,9],
                                                  'c':[12,13,14,15]
    
})

In [42]:
dataset_dic

<TensorSliceDataset shapes: {a: (), b: (), c: ()}, types: {a: tf.int32, b: tf.int32, c: tf.int32}>

In [43]:
for ele in dataset_dic:
    print(ele)

{'a': <tf.Tensor: shape=(), dtype=int32, numpy=1>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=6>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=12>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=2>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=7>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=13>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=3>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=8>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=14>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=4>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=9>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=15>}


In [44]:
import numpy as np

In [45]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 3, 4, 5, 6, 7]))

## 取出前4个元素

In [46]:
for ele in dataset.take(4): 
    print(ele.numpy())

1
2
3
4


In [47]:
next(iter(dataset.take(1)))

<tf.Tensor: shape=(), dtype=int32, numpy=1>

## 数据的乱序排布

In [48]:
dataset = dataset.shuffle(7)
dataset = dataset.repeat(count=2)

In [49]:
for ele in dataset: 
    print(ele.numpy())

7
1
3
5
2
6
4
7
2
6
5
4
3
1


## 每次出来3个元素

In [50]:
dataset = dataset.batch(3)

In [51]:
for ele in dataset: 
    print(ele.numpy())

[2 1 5]
[6 3 4]
[7 5 7]
[2 6 1]
[4 3]


## 使用函数对数据进行处理

In [52]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 3, 4, 5, 6, 7]))

In [53]:
dataset = dataset.map(tf.square)

In [54]:
for ele in dataset: 
    print(ele.numpy())

1
4
9
16
25
36
49


In [55]:
dataset

<MapDataset shapes: (), types: tf.int32>